### ISSUE TITLE
Tool does not allow edit of settings

### ISSUE THREAD

**Issue by grburgos** [storj-thirdparty/qnap-storagenode-app#19]
On the latest QNAP firmware (4.5.4.1741) the editing of settings of the storj app does not work. Being on the dashboard and then clicking on the edit of any of the values causes no change. To edit any setting the only option is to click setup and go through the entire process again.

**Comment by paragpadsumbiya** [comment]
Hello @grburgos 

If your node active then system will not allow to edit the settings so please make sure that your node stopped and also please install the latest version of the storjapp.

Thanks
Parag Padsumbiya

**Comment by paragpadsumbiya** [comment]
Hello @grburgos 

yeah it was issue due to content security policy in new firmware so there were some js errors.

But we have fixed them and release the new version.

https://github.com/storj-thirdparty/qnap-storagenode-app/releases/tag/v1.1.3
 
 Please try the new release and let us know your feedback.
